USE WAREHOUSE tasty_bytes_dbt_wh;
USE ROLE DBT_DEV_ROLE;

CREATE OR REPLACE TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_setup
	WAREHOUSE=TASTY_BYTES_DBT_WH
	AS EXECUTE DBT PROJECT "TASTY_BYTES_ANALYTICS_DB"."INTEGRATIONS"."FOOD_TRUCK_ANALYTICS_DBT_PROJECT" args='run --select tag:silver,tag:staging --target dev';

CREATE OR REPLACE TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_transformation
	WAREHOUSE=TASTY_BYTES_DBT_WH
	AFTER TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_setup
	AS EXECUTE DBT PROJECT "TASTY_BYTES_ANALYTICS_DB"."INTEGRATIONS"."FOOD_TRUCK_ANALYTICS_DBT_PROJECT" args='run --select tag:silver,tag:intermediate --target dev';

CREATE OR REPLACE TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_dataquality
	WAREHOUSE=TASTY_BYTES_DBT_WH
	AFTER TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_transformation
	AS EXECUTE DBT PROJECT "TASTY_BYTES_ANALYTICS_DB"."INTEGRATIONS"."FOOD_TRUCK_ANALYTICS_DBT_PROJECT" args='test --select tag:silver,tag:intermediate --target dev';

CREATE OR REPLACE TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_core_transformation
	WAREHOUSE=TASTY_BYTES_DBT_WH
	AFTER TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_dataquality
	AS EXECUTE DBT PROJECT "TASTY_BYTES_ANALYTICS_DB"."INTEGRATIONS"."FOOD_TRUCK_ANALYTICS_DBT_PROJECT" args='run --select tag:gold,tag:core --target dev';

CREATE OR REPLACE TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_core_dataquality
	WAREHOUSE=TASTY_BYTES_DBT_WH
	AFTER TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_core_transformation
	AS EXECUTE DBT PROJECT "TASTY_BYTES_ANALYTICS_DB"."INTEGRATIONS"."FOOD_TRUCK_ANALYTICS_DBT_PROJECT" args='test --select tag:gold,tag:core --target dev';

CREATE OR REPLACE TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_analytics_transformation
	WAREHOUSE=TASTY_BYTES_DBT_WH
	AFTER TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_core_dataquality
	AS EXECUTE DBT PROJECT "TASTY_BYTES_ANALYTICS_DB"."INTEGRATIONS"."FOOD_TRUCK_ANALYTICS_DBT_PROJECT" args='run --select tag:gold,tag:analytics --target dev';

CREATE OR REPLACE TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_analytics_dataquality
	WAREHOUSE=TASTY_BYTES_DBT_WH
	AFTER TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_analytics_transformation
	AS EXECUTE DBT PROJECT "TASTY_BYTES_ANALYTICS_DB"."INTEGRATIONS"."FOOD_TRUCK_ANALYTICS_DBT_PROJECT" args='test --select tag:gold,tag:analytics --target dev';

-- Task execution commands:
ALTER TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_setup RESUME;
ALTER TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_transformation RESUME;
ALTER TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_silver_staging_dataquality RESUME;
ALTER TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_core_transformation RESUME;
ALTER TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_core_dataquality RESUME;
ALTER TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_analytics_transformation RESUME;
ALTER TASK TASTY_BYTES_ANALYTICS_DB.INTEGRATIONS.tasty_bytes_gold_analytics_dataquality RESUME;
-- Summary: 7 enabled tasks, 0 disabled tasks
